// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuyixkzhghqtjjsxwmbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1eWl4a3poZ2hxdGpqc3h3bWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjE2MDcsImV4cCI6MjA1ODMzNzYwN30._JpoJB6NfIwFJINOtIM2iWHmXIk86CKiC-gfQKq8vmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);